### ISSUE TITLE
Hitting an error when query has more than 100 results

### ISSUE THREAD

**Issue by sandyarmstrong** [cmbrose/cosmosdb-powershell#6]
First of all, thank you for this tremendously useful module! It's been very useful to me on an almost daily basis.

Any time I do a query that would return more than 100 results (the default pagination value in the REST API according to https://docs.microsoft.com/en-us/rest/api/cosmos-db/querying-cosmosdb-resources-using-the-rest-api#pagination-of-query-results), I get an error. I end up processing the batch of 100 records and then querying/processing repeatedly until I get an empty result set.

Example call:

```pwsh
Search-CosmosDbRecords `
  -ResourceGroup $info.ResourceGroup `
  -Database $info.Database `
  -Container $info.Container `
  -Collection $info.Collection `
  -SubscriptionId $info.Subscription `
  -Query "SELECT * FROM c"
```

Example error:

```
Invoke-WebRequest: C:\Users\saarmst\Documents\PowerShell\Modules\cosmos-db\1.6\cosmos-db.psm1:187
Line |
 187 |      Invoke-WebRequest -Method $verb -Uri $url -Body $body -Headers $h …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"code":"BadRequest","message":"Message: {\"Errors\":[\"The continuation token specified in the request is malformed. Please re-run the query
     | without it and iterate.\"]}\r\nActivityId: #################, Request URI:
     | /apps/#################, RequestStats: \r\nRequestStartTime: 2020-12-31T18:37:15.8477694Z, RequestEndTime: 2020-12-31T18:37:15.8477694Z,  Number of regions attempted:1\r\nResponseTime: 2020-12-31T18:37:15.8477694Z, StoreResult: StorePhysicalAddress: rntbd://###################, LSN: ########, GlobalCommittedLsn: ########, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1###########, UsingLocalLSN: True, TransportException: null, ResourceType: Document, OperationType: Query\r\n, SDK: Microsoft.Azure.Documents.Common/2.11.0"}
```

I haven't ruled out the possibility that some other process is deleting records, which is known to potentially break the continuation token when paginating, but it happens so consistently that I think something else must be going on.

**Comment by cmbrose** [comment]
Thanks for reporting @sandyarmstrong!

I've been having trouble repro-ing for some reason. Could you get your version of the module `get-module cosmos-db`? It should be at least > `1.5`, `1.7` is the latest.

Also, could you try and grab a fiddler trace of the failed request and the one right before it? You'll need to use this to let fiddler work: ` Use-CosmosDbInternalFlag -enableFiddlerDebugging`

Thanks!

**Comment by cmbrose** [comment]
Another thing to try would be to use the `-DisableExtraFeatures` switch in the `Search` command (which is also available in the wrapper module you'll using :smile:) - that will help narrow down the codepath may have the bug

**Comment by sandyarmstrong** [comment]
This was tested with 1.6. I get the same error with 1.7. Adding `-DisableExtraFeatures` changes the error slightly:

```
❯ $records = Search-CosmosDbRecords -ResourceGroup $info.ResourceGroup -Database $info.Database -Container $info.Container -Collection $info.Collection -SubscriptionId $info.Subscription -Query "SELECT * FROM c" -DisableExtraFeatures
Invoke-WebRequest: C:\Users\saarmst\Documents\PowerShell\Modules\cosmos-db\1.7\cosmos-db.psm1:187
Line |
 187 |      Invoke-WebRequest -Method $verb -Uri $url -Body $body -Headers $h …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"code":"BadRequest","message":"Invalid Continuation Token\r\nActivityId:
     | ##################, Microsoft.Azure.Documents.Common/2.11.0"}
```

**Comment by sandyarmstrong** [comment]
OK, looks pretty straightforward. The initial request has this header:

```
x-ms-continuation: {"token":"-RID:~eLYoAKjsbghKQgEAAAAAAA==#RT:1#TRC:100#ISV:2#IEO:65551#QCF:1","range":{"min":"","max":"FF"}}
```

The continuation request has this:

```
x-ms-continuation: System.String[]
```

So it looks like powershell silliness interfering when you set the header on the continuation request.

**Comment by sandyarmstrong** [comment]
Yeah, according to https://docs.microsoft.com/en-us/dotnet/api/microsoft.powershell.commands.webresponseobject.headers?view=powershellsdk-7.0.0#Microsoft_PowerShell_Commands_WebResponseObject_Headers , the values in the `Headers` dictionary are `IEnumerable<string>`. But when you pass headers to `Invoke-WebRequest`, I'll bet they need to be strings, lol.

**Comment by sandyarmstrong** [comment]
Works for me:

```diff
diff --git a/cosmos-db/cosmos-db.psm1 b/cosmos-db/cosmos-db.psm1
index 1f7adb4..d778ef1 100644
--- a/cosmos-db/cosmos-db.psm1
+++ b/cosmos-db/cosmos-db.psm1
@@ -196,7 +196,7 @@ Function Invoke-CosmosDbApiRequestWithContinuation([string]$verb, [string]$url,

         while ($response.Headers["x-ms-continuation"])
         {
-            $headers["x-ms-continuation"] = $response.Headers["x-ms-continuation"];
+            $headers["x-ms-continuation"] = $response.Headers["x-ms-continuation"][0];

             $response = Invoke-CosmosDbApiRequest -Verb $verb -Url $url -Body $body -Headers $headers
             $response
```

**Comment by sandyarmstrong** [comment]
In case it matters for reproducibility, I'm using PowerShell 7.1.0.

**Comment by sandyarmstrong** [comment]
Yeah, this seems to be a difference in behavior between PowerShell 5 and 7. Bummer!

**Comment by cmbrose** [comment]
Thanks for all the follow up here! Made it super easy on my end - PR is here: https://github.com/cmbrose/cosmosdb-powershell/pull/7

**Comment by sandyarmstrong** [comment]
Cool! For the record, it's actually ps6 (core) where the change started. You can also check if $PSVersionTable.PSEdition is "Core".

**Comment by cmbrose** [comment]
Ahh - I misread the Url and thought it broken in 7 :) Thanks for calling that out - updated to just check "Core" instead
